"""

Revision ID: 02e957fe4bc0
Revises: a241d136058d
Create Date: 2026-01-04 01:50:02.964585

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e957fe4bc0'
down_revision: Union[str, Sequence[str], None] = 'a241d136058d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followup',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('requested_date', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ncr_id', sa.UUID(), nullable=False),
    sa.Column('assgined_on', sa.DateTime(), nullable=False),
    sa.Column('completed_on', sa.DateTime(), nullable=False),
    sa.Column('auditor_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ncr_id'], ['ncr.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followup')
    # ### end Alembic commands ###
