"""empty message

Revision ID: 060a73ed1b67
Revises: 95dd98058113
Create Date: 2026-01-12 23:43:36.769568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060a73ed1b67'
down_revision: Union[str, Sequence[str], None] = '95dd98058113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
