"""empty message

Revision ID: 47d2c2a8d502
Revises: ed7f8e8fa919
Create Date: 2026-02-16 15:37:34.906910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '47d2c2a8d502'
down_revision: Union[str, Sequence[str], None] = 'ed7f8e8fa919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestionteam', sa.Column('suggestion_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('suggestionteam_ncr_id_fkey'), 'suggestionteam', type_='foreignkey')
    op.create_foreign_key(None, 'suggestionteam', 'suggestion', ['suggestion_id'], ['id'], ondelete='CASCADE')
    op.drop_column('suggestionteam', 'ncr_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestionteam', sa.Column('ncr_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'suggestionteam', type_='foreignkey')
    op.create_foreign_key(op.f('suggestionteam_ncr_id_fkey'), 'suggestionteam', 'ncr', ['ncr_id'], ['id'], ondelete='CASCADE')
    op.drop_column('suggestionteam', 'suggestion_id')
    # ### end Alembic commands ###
