"""empty message

Revision ID: 51bf226e62a8
Revises: 853c901c8fde
Create Date: 2026-02-26 00:35:03.320072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51bf226e62a8'
down_revision: Union[str, Sequence[str], None] = '853c901c8fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('franchiseauditchecklist', sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'DRAFTED', name='checkliststatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('franchiseauditchecklist', 'status')
    # ### end Alembic commands ###
