"""empty message

Revision ID: 5b29339d9f2b
Revises: e9e0479c906b
Create Date: 2025-12-29 22:30:04.645386

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b29339d9f2b'
down_revision: Union[str, Sequence[str], None] = 'e9e0479c906b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdepartment', sa.Column('role_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'userdepartment', 'userrole', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userdepartment', type_='foreignkey')
    op.drop_column('userdepartment', 'role_id')
    # ### end Alembic commands ###
