"""empty message

Revision ID: 5c0d207047d4
Revises: 486e845eedf4
Create Date: 2026-02-27 00:20:55.362689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0d207047d4'
down_revision: Union[str, Sequence[str], None] = '486e845eedf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internalauditorschecklist', sa.Column('internal_audit_number_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'internalauditorschecklist', 'auditinfo', ['internal_audit_number_id'], ['id'], ondelete='CASCADE')
    op.drop_column('internalauditorschecklist', 'internal_audit_number')
    op.alter_column('userdepartment', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('userdepartment', 'department_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('userdepartment', 'role_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userdepartment', 'role_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('userdepartment', 'department_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('userdepartment', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('internalauditorschecklist', sa.Column('internal_audit_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'internalauditorschecklist', type_='foreignkey')
    op.drop_column('internalauditorschecklist', 'internal_audit_number_id')
    # ### end Alembic commands ###
