"""empty message

Revision ID: 5f6431e1c7e6
Revises: 47d2c2a8d502
Create Date: 2026-02-24 00:58:41.267486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5f6431e1c7e6'
down_revision: Union[str, Sequence[str], None] = '47d2c2a8d502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internalauditobservationchecklist', sa.Column('internal_audit_number_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'internalauditobservationchecklist', 'auditinfo', ['internal_audit_number_id'], ['id'], ondelete='CASCADE')
    op.drop_column('internalauditobservationchecklist', 'internal_audit_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internalauditobservationchecklist', sa.Column('internal_audit_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'internalauditobservationchecklist', type_='foreignkey')
    op.drop_column('internalauditobservationchecklist', 'internal_audit_number_id')
    # ### end Alembic commands ###
