"""empty message

Revision ID: 833950272787
Revises: f31a6ef20ade
Create Date: 2026-02-15 23:31:03.888858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '833950272787'
down_revision: Union[str, Sequence[str], None] = 'f31a6ef20ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audit_info_id', sa.UUID(), nullable=False),
    sa.Column('expected_date_of_completion', sa.DateTime(), nullable=True),
    sa.Column('actual_date_of_completion', sa.DateTime(), nullable=True),
    sa.Column('suggestion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('corrective_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['audit_info_id'], ['auditinfo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestionteam',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ncr_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('CREATED_BY', 'HOD', 'AUDITEE', name='suggestionteamrole'), nullable=False),
    sa.ForeignKeyConstraint(['ncr_id'], ['ncr.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestionteam')
    op.drop_table('suggestion')
    # ### end Alembic commands ###
