"""

Revision ID: 897080e42fb8
Revises: 341894525d5f
Create Date: 2026-01-04 02:28:33.760704

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897080e42fb8'
down_revision: Union[str, Sequence[str], None] = '341894525d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edcrequest',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ncr_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('new_edc', sa.DateTime(), nullable=False),
    sa.Column('old_edc', sa.DateTime(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='edcstatus'), nullable=False),
    sa.ForeignKeyConstraint(['ncr_id'], ['ncr.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edcrequest')
    # ### end Alembic commands ###
