"""empty message

Revision ID: 95c9f03342a5
Revises: 5c0d207047d4
Create Date: 2026-02-28 02:14:38.397422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '95c9f03342a5'
down_revision: Union[str, Sequence[str], None] = '5c0d207047d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brcpwarehousechecklist', sa.Column('supplier', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brcpwarehousechecklist', 'supplier')
    # ### end Alembic commands ###
