"""empty message

Revision ID: 95dd98058113
Revises: c092508ab100
Create Date: 2026-01-11 23:50:51.908170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95dd98058113'
down_revision: Union[str, Sequence[str], None] = 'c092508ab100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('followup', 'auditor_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
