"""

Revision ID: a241d136058d
Revises: d60d030f381b
Create Date: 2026-01-04 00:38:23.710617

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a241d136058d'
down_revision: Union[str, Sequence[str], None] = 'd60d030f381b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ncrfiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ncr_id', sa.UUID(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sa.Enum('NCR_FILE', 'FOLLOWUP_FILE', name='ncrfiletype'), nullable=False),
    sa.ForeignKeyConstraint(['ncr_id'], ['ncr.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ncrteam',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ncr_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('CREATED_BY', 'HOD', 'FOLLOWUP_AUDITOR', 'AUDITEE', name='ncrteamrole'), nullable=False),
    sa.ForeignKeyConstraint(['ncr_id'], ['ncr.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ncr', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ncr', sa.Column('objective_evidence', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ncr', sa.Column('requirement', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ncr', sa.Column('correction', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ncr', sa.Column('root_cause', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ncr', sa.Column('systematic_corrective_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ncr', sa.Column('corrective_action_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ncr', sa.Column('expected_date_of_completion', sa.DateTime(), nullable=True))
    op.add_column('ncr', sa.Column('actual_date_of_completion', sa.DateTime(), nullable=True))
    op.add_column('ncr', sa.Column('edc_given_date', sa.DateTime(), nullable=True))
    op.add_column('ncr', sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ncr', sa.Column('followup_observations', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ncr', sa.Column('followup_date', sa.DateTime(), nullable=True))
    op.add_column('ncr', sa.Column('rejected_reson', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ncr', sa.Column('rejected_count', sa.Integer(), nullable=True))
    op.add_column('ncr', sa.Column('closed_on', sa.DateTime(), nullable=True))
    op.alter_column('ncr', 'main_clause',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ncr', 'sub_clause',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ncr', 'ss_clause',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ncr', 'ss_clause',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ncr', 'sub_clause',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ncr', 'main_clause',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('ncr', 'closed_on')
    op.drop_column('ncr', 'rejected_count')
    op.drop_column('ncr', 'rejected_reson')
    op.drop_column('ncr', 'followup_date')
    op.drop_column('ncr', 'followup_observations')
    op.drop_column('ncr', 'remarks')
    op.drop_column('ncr', 'edc_given_date')
    op.drop_column('ncr', 'actual_date_of_completion')
    op.drop_column('ncr', 'expected_date_of_completion')
    op.drop_column('ncr', 'corrective_action_details')
    op.drop_column('ncr', 'systematic_corrective_action')
    op.drop_column('ncr', 'root_cause')
    op.drop_column('ncr', 'correction')
    op.drop_column('ncr', 'requirement')
    op.drop_column('ncr', 'objective_evidence')
    op.drop_column('ncr', 'description')
    op.drop_table('ncrteam')
    op.drop_table('ncrfiles')
    # ### end Alembic commands ###
