"""empty message

Revision ID: aaa193246baa
Revises: 482919da4b4a
Create Date: 2025-12-31 00:10:21.928265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'aaa193246baa'
down_revision: Union[str, Sequence[str], None] = '482919da4b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit', sa.Column('ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('audit', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('audit', sa.Column('standard', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('audit', sa.Column('schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('audit', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('audit', sa.Column('end_date', sa.DateTime(), nullable=False))
    op.add_column('audit', sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('audit', sa.Column('plant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'audit', 'plant', ['plant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('audit', 'audit_standard')
    op.drop_column('audit', 'audit_schedule')
    op.drop_column('audit', 'audit_type')
    op.drop_column('audit', 'audit_ref')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit', sa.Column('audit_ref', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('audit', sa.Column('audit_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('audit', sa.Column('audit_schedule', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('audit', sa.Column('audit_standard', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'audit', type_='foreignkey')
    op.drop_column('audit', 'plant_id')
    op.drop_column('audit', 'remarks')
    op.drop_column('audit', 'end_date')
    op.drop_column('audit', 'start_date')
    op.drop_column('audit', 'schedule')
    op.drop_column('audit', 'standard')
    op.drop_column('audit', 'type')
    op.drop_column('audit', 'ref')
    # ### end Alembic commands ###
