"""empty message

Revision ID: b88a5e4f86c8
Revises: 5b29339d9f2b
Create Date: 2025-12-30 00:03:06.319240

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88a5e4f86c8'
down_revision: Union[str, Sequence[str], None] = '5b29339d9f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Enum('ADMIN', 'USER', name='roleenum'), nullable=False))
    op.drop_constraint(op.f('user_role_id_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('user_role_id_fkey'), 'user', 'userrole', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
