"""empty message

Revision ID: ce1971130947
Revises: aaa193246baa
Create Date: 2026-01-01 01:12:38.989855

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1971130947'
down_revision: Union[str, Sequence[str], None] = 'aaa193246baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditinfo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=False),
    sa.Column('to_date', sa.DateTime(), nullable=False),
    sa.Column('closed_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='auditinfostatus'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditteam',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('audit_info_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('AUDITOR', 'TRAINEE', 'AUDITEE_COORDINATOR', 'AUDITEE', name='auditteamrole'), nullable=False),
    sa.ForeignKeyConstraint(['audit_info_id'], ['auditinfo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditteam')
    op.drop_table('auditinfo')
    # ### end Alembic commands ###
