"""empty message

Revision ID: d44fd8062936
Revises: e09c4d97b9bd
Create Date: 2026-01-11 23:36:40.611773

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44fd8062936'
down_revision: Union[str, Sequence[str], None] = 'e09c4d97b9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followup', sa.Column('observations', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followup', 'observations')
    # ### end Alembic commands ###
