"""

Revision ID: d60d030f381b
Revises: 31933c848762
Create Date: 2026-01-01 02:14:01.845577

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd60d030f381b'
down_revision: Union[str, Sequence[str], None] = '31933c848762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auditinfo', sa.Column('audit_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'auditinfo', 'audit', ['audit_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auditinfo', type_='foreignkey')
    op.drop_column('auditinfo', 'audit_id')
    # ### end Alembic commands ###
