"""empty message

Revision ID: e9e0479c906b
Revises: 087ecba12dda
Create Date: 2025-12-28 23:15:36.546220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e0479c906b'
down_revision: Union[str, Sequence[str], None] = '087ecba12dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'userrole', ['role'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userrole', type_='unique')
    # ### end Alembic commands ###
