"""empty message

Revision ID: ed7f8e8fa919
Revises: 833950272787
Create Date: 2026-02-15 23:35:40.276561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ed7f8e8fa919'
down_revision: Union[str, Sequence[str], None] = '833950272787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    
    op.execute("""
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type WHERE typname = 'suggestionstatus'
    ) THEN
        CREATE TYPE suggestionstatus AS ENUM (
            'CREATED',
            'ACCEPTED',
            'CLOSED',
            'REJECTED'
            
        );
    END IF;
END
$$;
""")

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestion', sa.Column('status', sa.Enum('CREATED', 'ACCEPTED', 'CLOSED', 'REJECTED', name='suggestionstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggestion', 'status')
    # ### end Alembic commands ###
