"""checklist tables

Revision ID: f31a6ef20ade
Revises: 0944f72ba092
Create Date: 2026-02-07 01:47:10.372605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f31a6ef20ade'
down_revision: Union[str, Sequence[str], None] = '0944f72ba092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brcpwarehousechecklist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('internal_audit_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('warehouse_incharge', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'DRAFTED', name='checkliststatus'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('franchiseauditchecklist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('division', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audit_area', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('franchise_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audit_date', sa.Date(), nullable=True),
    sa.Column('suggestions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('service_engineer_sign', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internalauditobservationchecklist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('internal_audit_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('division', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audit_area', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'DRAFTED', name='checkliststatus'), nullable=False),
    sa.Column('auditee_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internalauditorschecklist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('internal_audit_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('division', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audit_area', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'DRAFTED', name='checkliststatus'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batteryrefreshstatus',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_due_qty', sa.Integer(), nullable=True),
    sa.Column('ageing_91_180', sa.Integer(), nullable=True),
    sa.Column('refresh_91_180_date', sa.Date(), nullable=True),
    sa.Column('ageing_181_270', sa.Integer(), nullable=True),
    sa.Column('refresh_181_270_date', sa.Date(), nullable=True),
    sa.Column('ageing_271_360', sa.Integer(), nullable=True),
    sa.Column('refresh_271_360_date', sa.Date(), nullable=True),
    sa.Column('ageing_361_450', sa.Integer(), nullable=True),
    sa.Column('refresh_361_450_date', sa.Date(), nullable=True),
    sa.Column('ageing_451_540', sa.Integer(), nullable=True),
    sa.Column('refresh_451_540_date', sa.Date(), nullable=True),
    sa.Column('ageing_above_540', sa.Integer(), nullable=True),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['brcpwarehousechecklist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chargerinfrastructure',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('charger_serial_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('make', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year_of_mfg', sa.Integer(), nullable=True),
    sa.Column('rating', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('channels_working', sa.Integer(), nullable=True),
    sa.Column('channels_not_working', sa.Integer(), nullable=True),
    sa.Column('calibration_due_on', sa.Date(), nullable=True),
    sa.Column('work_instruction_available', sa.Boolean(), nullable=True),
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['brcpwarehousechecklist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('franchiseauditobservation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('requirement', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['franchiseauditchecklist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internalauditobservationchecklistitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('sl_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('procedure_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qms_check_point', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clause_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ncr_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['internalauditobservationchecklist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internalauditorschecklistitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('activity_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('applicable_functions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audit_findings', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['internalauditorschecklist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measuringinstrument',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('instrument_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('imte_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('make', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('serial_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('calibration_due_on', sa.Date(), nullable=True),
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['brcpwarehousechecklist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouseadditionalinfo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.Column('operating_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_manpower', sa.Integer(), nullable=True),
    sa.Column('refresh_charging_manpower', sa.Integer(), nullable=True),
    sa.Column('power_cut_hours_per_day', sa.Float(), nullable=True),
    sa.Column('dg_available', sa.Boolean(), nullable=True),
    sa.Column('additional_information', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['brcpwarehousechecklist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouseadditionalinfo')
    op.drop_table('measuringinstrument')
    op.drop_table('internalauditorschecklistitem')
    op.drop_table('internalauditobservationchecklistitem')
    op.drop_table('franchiseauditobservation')
    op.drop_table('chargerinfrastructure')
    op.drop_table('batteryrefreshstatus')
    op.drop_table('internalauditorschecklist')
    op.drop_table('internalauditobservationchecklist')
    op.drop_table('franchiseauditchecklist')
    op.drop_table('brcpwarehousechecklist')
    # ### end Alembic commands ###
